name: Frontend Site Build Job

on:
  push:
    tags:
      - v*.*.*-f

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10.15.3'
      - run: cd ./frontend && sh ./env.sh && yarn && yarn generate && mv dist ../

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './dist'